/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "category",
      label: "Om",
      items: [
        "komigang",
        {
          type: "autogenerated",
          dirName: "om",
        },
      ],
    },
    {
      "API'er": [
        "api/aksjebeholdning",
        "api/aksjonaerivirksomhet",
        "api/aktivkonto",
        "api/arbeidsforholdioppdrag",
        "api/arbeidsgiveravgift",
        "api/avregning",
        "api/beregnetskatt",
        "api/beregnetskattupersonlig",
        "api/bsu",
        "api/formuesgrunnlageiendomsskatt",
        "api/hendelser",
        "api/inntekt",
        "api/inntektsmottakere",
        "api/mva_meldingsopplysning",
        "api/mvamelding",
        "api/mvaregisteravgiftssubjekt",
        "api/naeringsspesifikasjon",
        "api/omregistreringsavgift",
        "api/oppdragutenlandskevirksomheter",
        "api/pgi",
        "api/pgi_folketrygden",
        "api/restanser",
        "api/sistetilgjengeligeskatteoppgjoer",
        "api/skatteberegningsgrunnlagupersonlig",
        "api/skattemelding",
        "api/skattemeldingupersonlig",
        "api/skatteplikt",
        "api/skattepliktupersonlig",
        "api/skattepliktig",
        "api/spesifisertsummertskattegrunnlag",
        "api/summertskattegrunnlag",
        "api/summertskattegrunnlagupersonlig",
        "api/tilleggsskatt",
        "api/tjenestepensjonsavtale",
        "api/trukketkildeskattpaaloenn",
      ],
    },
    { Anvendelsesområder: [{ type: "autogenerated", dirName: "anvendelsesomraader" }] },
    { Test: [{ type: "autogenerated", dirName: "test" }] },
    {
      type: "doc",
      label: "Kontakt oss",
      id: "kontaktoss",
    },
  ],
};

module.exports = sidebars;
